### ISSUE TITLE
Where are the C# examples?

### ISSUE THREAD

**Issue by GeorgeS2019** [MikeSchulze/gdUnit3-examples#1]

**Comment by MikeSchulze** [comment]
Will be add within the next release v2.3.0

**Comment by GeorgeS2019** [comment]
Hi, v2.3.0 is here, still waiting for c# example :-)

**Comment by MikeSchulze** [comment]
sorry no ;) The v2.3.0 is not released yet.
The master branch is work in progress.
![image](https://user-images.githubusercontent.com/347037/185635556-4dbbaec4-71d8-4b1f-8634-eec26c1b5221.png)

**Comment by GeorgeS2019** [comment]
@MikeSchulze 
Can it run this NOW? I have installed VSCode Extension.

**Comment by GeorgeS2019** [comment]
![ZUVhz2kCRr](https://user-images.githubusercontent.com/49812372/185457644-11f37caa-38e7-4b86-9f7b-757a21c0dc33.gif)

**Comment by GeorgeS2019** [comment]
this is solved [now](https://github.com/MikeSchulze/gdUnit4Mono/issues/35)
